### ISSUE TITLE
Problem on detecting hungarian(hu)

### ISSUE THREAD

**Issue by xufuou** [Unbabel/unbabel-langid#22]
I tried to detect this text from hungarian duolingo website:

> "A duolingós tanulás szórakoztat és függőséget okoz. Szerezz pontokat a jó válaszok után, fuss versenyt az idővel, és lépj egyre magasabb szintekre! Falatnyi leckéink hatékonyak, és hogy a módszer működik, arra bizonyítékunk van. Használd ki jobban szüneteid, utazásaid idejét iPhone- és Android-alkalmazásainkkal. Töltsd le és nézd meg, mivel érdemeltük ki az Apple és a Google legnagyobb elismerését!
> Az életek révén maradhatsz meg a leckékben! Helytelen válasz esetén egy-egy élet odavész. Ha elfogynak, újrakezdheted, és megpróbálhatod ismét."
_source:https://hu.duolingo.com/_

It returned es

Same goes to serbian I guess:

> Najděte si to nejlepší ubytování
> Ať už se chystáte kamkoliv, Vaše cesta začíná zde
> Najděte si to nejlepší ubytování
> Ať už se chystáte kamkoliv, Vaše cesta začíná zde
_source:http://www.booking.com/index.cs.html_

 It also returns es

**Comment by gracaninja** [comment]
Tell Gonçalo to look into it. This should not tell ES with 100% sure.

João

2016-07-18 11:17 GMT+01:00 Xu Fu Ou <notifications@github.com>:
